before_script:
  - id
  - uname -a

build:
  image: ubuntu:bionic
  script:
    - apt-get update -qq
    - apt-get install -y -qq git python3 python3-setuptools build-essential pkg-config gir1.2-glib-2.0
    - git clone https://github.com/mesonbuild/meson.git
    - cd meson
    - python3 setup.py install
    - cd ..
    - meson --version
    - mkdir builddir
    - meson builddir
    - cd builddid
    - ninja