stages:
  - build

build-meson:
  image: archlinux:latest
  stage: build
  before_script:
    - pacman -Syu --noconfirm
    - pacman -S --noconfirm
      meson gcc dbus gcr glib2 gobject-introspection
      gtk-doc gtk3 json-glib krb5 libsecret
      libsoup3 librest vala webkit2gtk-4.1
  script:
    - meson setup -Dgtk_doc=true _build
    - meson compile -C _build
    - meson test -C _build
