stages:
  - build

build-meson:
  image: fedora:latest
  stage: build
  before_script:
    - dnf update -y
    - dnf -y install
      meson gcc dbus-devel gcr-devel glib2-devel gobject-introspection-devel
      gtk-doc gtk3-devel json-glib-devel krb5-devel libsecret-devel
      libsoup-devel rest-devel vala webkit2gtk3-devel
  script:
    - meson setup -Dgtk_doc=true _build
    - meson compile -C _build
    - meson test -C _build
