stages:
  - build
  - analysis

build-meson:
  image: archlinux:latest
  stage: build
  before_script:
    - pacman -Syu --noconfirm
    - pacman -S --noconfirm
      meson git gcc dbus gcr-4 glib2 gobject-introspection
      gtk-doc gtk4 json-glib krb5 libadwaita libsecret
      libsoup3 python-packaging vala
  script:
    - meson setup -Dgtk_doc=true _build
    - meson compile -C _build
    - meson test -C _build
    - meson install -C _build

build-meson-nobackend:
  image: fedora:latest
  stage: build
  before_script:
    - dnf update -y
    - dnf -y install
      meson gcc dbus-devel glib2-devel gobject-introspection-devel
      gtk4-devel rest-devel vala
  script:
    - meson setup -Dgtk_doc=false -Dgoabackend=false _build
    - meson compile -C _build
    - meson test -C _build
    - meson install -C _build

clang-analyzer:
  image: fedora:latest
  stage: analysis
  variables:
    # Warnings from dependencies are irrelevant here
    CFLAGS: "-Wno-strict-prototypes -Wno-deprecated-declarations"
  before_script:
    - dnf update -y
    - dnf -y install
      clang clang-analyzer meson gcr-devel dbus-devel glib2-devel
      gobject-introspection-devel gtk4-devel krb5-devel libadwaita-devel
      libsecret-devel rest-devel vala
  script:
    - meson setup --buildtype=debug
                  -Dfedora=true
                  -Dgtk_doc=false
                  -Dman=false
                  -Dwerror=true
                  _scan_build
    - export SCANBUILD="$PWD/.gitlab-ci/scanbuild-wrapper.sh"
    - ninja -C _scan_build scan-build
  after_script:
    - .gitlab-ci/scanbuild-plist-to-junit.py _scan_build/meson-logs/scanbuild/ > _scan_build/junit-scan-build.xml
  artifacts:
    paths:
      - _scan_build/meson-logs
    reports:
      junit: "_scan_build/junit-scan-build.xml"
  allow_failure: true

gcc-analyzer:
  image: fedora:latest
  stage: analysis
  variables:
    # `-Wanalyzer-null-*` is absurd, and the others are irrelevant here
    CFLAGS: "-fanalyzer -Wno-analyzer-null-argument -Wno-analyzer-null-dereference -Wno-strict-prototypes -Wno-deprecated-declarations"
  before_script:
    - dnf update -y
    - dnf -y install
      meson gcc gcr-devel dbus-devel glib2-devel gobject-introspection-devel
      gtk4-devel krb5-devel libadwaita-devel libsecret-devel rest-devel vala
  script:
    - meson setup --buildtype=debug
                  -Dfedora=true
                  -Dgtk_doc=false
                  -Dman=false
                  -Dwerror=true
                  _build
    - meson compile -C _build
  allow_failure: true

