include:
  - component: gitlab.gnome.org/GNOME/citemplates/release-service@master
    inputs:
      job-stage: release
      dist-job-name: build-full
      tarball-artifact-path: "_build/meson-dist/$CI_PROJECT_NAME-$CI_COMMIT_TAG.tar.xz"

stages:
  - review
  - build
  - analysis
  - deploy
  - release

potfile_check:
  image: fedora:latest
  stage: review
  script:
    - ./.gitlab-ci/check-potfiles.sh

build:
  image: fedora:latest
  stage: build
  before_script:
    - dnf update -y
    - dnf -y install
      meson gcc dbus-devel glib2-devel gobject-introspection-devel
      gtk4-devel rest-devel vala
  script:
    - meson setup -Ddocumentation=false -Dgoabackend=false _build
    - meson compile -C _build
    - meson test -C _build
    - meson install -C _build

build-full:
  image: fedora:latest
  stage: build
  before_script:
    - dnf update -y
    - dnf -y install dnf-plugins-core
      meson git gcc dbus-devel docbook-style-xsl gcr-devel gi-docgen glib2-devel
      gobject-introspection-devel gtk4-devel json-glib-devel krb5-devel
      libadwaita-devel libsecret-devel libsoup3-devel rest-devel vala
    - dnf -y builddep gtk4 libadwaita
  script:
    - meson setup -Ddocumentation=true
                  -Dfedora=true
                  _build
    - meson compile -C _build
    - meson test -C _build
    - meson install -C _build
    - meson dist -C _build
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    when: always
    paths:
      - _build/doc
      - _build/meson-dist/*.tar.xz

clang-analyzer:
  image: fedora:latest
  stage: analysis
  variables:
    # Warnings from dependencies are irrelevant here
    CFLAGS: "-Wno-strict-prototypes -Wno-deprecated-declarations"
  before_script:
    - dnf update -y
    - dnf -y install dnf-plugins-core
      clang clang-analyzer meson git gcr-devel dbus-devel gi-docgen glib2-devel
      gobject-introspection-devel gtk4-devel krb5-devel libadwaita-devel
      libsecret-devel rest-devel vala
    - dnf -y builddep gtk4 libadwaita
  script:
    - meson setup --buildtype=debug
                  -Dfedora=true
                  -Ddocumentation=false
                  -Dintrospection=false
                  -Dman=false
                  -Dwerror=true
                  _scan_build
    - export SCANBUILD="$PWD/.gitlab-ci/scanbuild-wrapper.sh"
    - ninja -C _scan_build scan-build
  after_script:
    - .gitlab-ci/scanbuild-plist-to-junit.py _scan_build/meson-logs/scanbuild/ > _scan_build/junit-scan-build.xml
  artifacts:
    paths:
      - _scan_build/meson-logs
    reports:
      junit: "_scan_build/junit-scan-build.xml"
  allow_failure: true

gcc-analyzer:
  image: fedora:latest
  stage: analysis
  variables:
    # `-Wanalyzer-null-*` is absurd, and the others are irrelevant here
    CFLAGS: "-fanalyzer -Wno-analyzer-null-argument -Wno-analyzer-null-dereference -Wno-strict-prototypes -Wno-deprecated-declarations"
  before_script:
    - dnf update -y
    - dnf -y install dnf-plugins-core
      meson git gcc gcr-devel dbus-devel glib2-devel gobject-introspection-devel
      gtk4-devel krb5-devel libadwaita-devel libsecret-devel rest-devel vala
    - dnf -y builddep gtk4 libadwaita
  script:
    - meson setup --buildtype=debug
                  -Dfedora=true
                  -Ddocumentation=false
                  -Dman=false
                  -Dwerror=true
                  _build
    - meson compile -C _build
  allow_failure: true

pages:
  stage: deploy
  dependencies:
  - build-full
  script:
  - mv _build/doc/gnome-online-accounts/Goa-1.0 public
  artifacts:
    paths:
    - public
  only:
  - master

